package kr.sofac.jangsisters.config;

public enum EnumPreference {
    USER_ID, FOLLOWERS, BOOKMARKS, POST_ID, URI, POST, UPDATED_PROFILE, MY_PROFILE, IS_AUTHORIZATION, GOOGLE_CLOUD_PREFERENCE, APP_PREFERENCES, CATEGORY_PREF, VERSION_CATEGORIES, MY_USER;
}
